[2025-06-19T01:17:18.770+0000] {processor.py:161} INFO - Started process (PID=51382) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:17:18.771+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:17:18.772+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:18.771+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:17:18.774+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:18.774+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:17:18.775+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:17:18.789+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.029 seconds
[2025-06-19T01:17:49.307+0000] {processor.py:161} INFO - Started process (PID=51418) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:17:49.308+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:17:49.309+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:49.309+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:17:49.312+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:49.311+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:17:49.313+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:17:49.327+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.034 seconds
[2025-06-19T01:18:19.722+0000] {processor.py:161} INFO - Started process (PID=51454) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:18:19.723+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:18:19.724+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:19.724+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:18:19.727+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:19.726+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:18:19.728+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:18:19.744+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.032 seconds
[2025-06-19T01:18:50.253+0000] {processor.py:161} INFO - Started process (PID=51490) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:18:50.255+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:18:50.256+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:50.256+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:18:50.260+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:50.259+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:18:50.261+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:18:50.278+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.033 seconds
[2025-06-19T01:19:21.153+0000] {processor.py:161} INFO - Started process (PID=51532) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:19:21.154+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:19:21.155+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:21.155+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:19:21.157+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:21.157+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:19:21.158+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:19:21.172+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.028 seconds
[2025-06-19T01:19:51.776+0000] {processor.py:161} INFO - Started process (PID=51568) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:19:51.777+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:19:51.778+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:51.778+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:19:51.782+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:51.781+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:19:51.783+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:19:51.796+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.027 seconds
[2025-06-19T01:20:22.191+0000] {processor.py:161} INFO - Started process (PID=51604) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:20:22.192+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:20:22.193+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:22.192+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:20:22.195+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:22.194+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:20:22.196+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:20:22.212+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.028 seconds
[2025-06-19T01:20:52.651+0000] {processor.py:161} INFO - Started process (PID=51640) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:20:52.653+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:20:52.655+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:52.654+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:20:52.660+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:52.658+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:20:52.661+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:20:52.681+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.037 seconds
[2025-06-19T01:21:23.124+0000] {processor.py:161} INFO - Started process (PID=51676) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:21:23.125+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:21:23.126+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:23.126+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:21:23.129+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:23.128+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:21:23.130+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:21:23.151+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.035 seconds
[2025-06-19T01:21:54.126+0000] {processor.py:161} INFO - Started process (PID=51712) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:21:54.127+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:21:54.128+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:54.127+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:21:54.131+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:54.130+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:21:54.132+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:21:54.149+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.036 seconds
[2025-06-19T01:22:24.585+0000] {processor.py:161} INFO - Started process (PID=51748) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:22:24.586+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:22:24.587+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:24.587+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:22:24.590+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:24.589+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:22:24.590+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:22:24.605+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.029 seconds
[2025-06-19T01:22:55.185+0000] {processor.py:161} INFO - Started process (PID=51784) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:22:55.186+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:22:55.187+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:55.187+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:22:55.189+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:55.189+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:22:55.190+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:22:55.206+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.030 seconds
[2025-06-19T01:23:26.050+0000] {processor.py:161} INFO - Started process (PID=51820) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:23:26.051+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:23:26.052+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:26.052+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:23:26.054+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:26.054+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:23:26.055+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:23:26.069+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.026 seconds
[2025-06-19T01:23:56.589+0000] {processor.py:161} INFO - Started process (PID=51856) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:23:56.590+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:23:56.591+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:56.591+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:23:56.594+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:56.593+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:23:56.595+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:23:56.619+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.038 seconds
[2025-06-19T01:24:27.264+0000] {processor.py:161} INFO - Started process (PID=51892) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:24:27.265+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:24:27.267+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:27.266+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:24:27.269+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:27.269+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:24:27.270+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:24:27.285+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.029 seconds
[2025-06-19T01:24:57.752+0000] {processor.py:161} INFO - Started process (PID=51928) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:24:57.753+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:24:57.754+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:57.754+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:24:57.756+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:57.756+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:24:57.757+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:24:57.771+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.028 seconds
[2025-06-19T01:25:28.391+0000] {processor.py:161} INFO - Started process (PID=51964) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:25:28.392+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:25:28.393+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:28.393+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:25:28.396+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:28.395+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:25:28.397+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:25:28.412+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.028 seconds
[2025-06-19T01:25:58.947+0000] {processor.py:161} INFO - Started process (PID=52000) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:25:58.948+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:25:58.950+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:58.949+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:25:58.954+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:58.953+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:25:58.955+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:25:58.976+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.038 seconds
[2025-06-19T01:26:29.649+0000] {processor.py:161} INFO - Started process (PID=52036) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:26:29.661+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:26:29.663+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:26:29.662+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:26:29.670+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:26:29.668+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:26:29.671+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:26:29.723+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.114 seconds
[2025-06-19T01:27:00.243+0000] {processor.py:161} INFO - Started process (PID=52072) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:27:00.244+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:27:00.244+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:00.244+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:27:00.247+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:00.246+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:27:00.249+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:27:00.265+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.030 seconds
[2025-06-19T01:27:30.784+0000] {processor.py:161} INFO - Started process (PID=52108) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:27:30.785+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:27:30.786+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:30.786+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:27:30.790+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:30.789+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:27:30.791+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:27:30.806+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.030 seconds
[2025-06-19T01:28:01.300+0000] {processor.py:161} INFO - Started process (PID=52144) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:28:01.301+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:28:01.302+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:01.302+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:28:01.306+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:01.305+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:28:01.307+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:28:01.326+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.035 seconds
[2025-06-19T01:28:32.025+0000] {processor.py:161} INFO - Started process (PID=52180) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:28:32.026+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:28:32.027+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:32.027+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:28:32.030+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:32.030+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:28:32.032+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:28:32.053+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.038 seconds
[2025-06-19T01:29:02.734+0000] {processor.py:161} INFO - Started process (PID=52216) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:29:02.736+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:29:02.738+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:02.737+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:29:02.742+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:02.741+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:29:02.743+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:29:02.771+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.050 seconds
[2025-06-19T01:29:32.927+0000] {processor.py:161} INFO - Started process (PID=52252) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:29:32.928+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:29:32.929+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:32.929+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:29:32.933+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:32.932+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:29:32.934+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:29:32.956+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.039 seconds
[2025-06-19T01:30:03.159+0000] {processor.py:161} INFO - Started process (PID=52288) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:30:03.160+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:30:03.161+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:03.161+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:30:03.165+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:03.164+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:30:03.166+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:30:03.186+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.038 seconds
[2025-06-19T01:30:33.906+0000] {processor.py:161} INFO - Started process (PID=52324) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:30:33.907+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:30:33.908+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:33.908+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:30:33.911+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:33.910+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:30:33.912+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:30:33.930+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.033 seconds
[2025-06-19T01:31:04.403+0000] {processor.py:161} INFO - Started process (PID=52360) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:31:04.404+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:31:04.405+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:04.404+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:31:04.408+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:04.407+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:31:04.409+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:31:04.429+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.036 seconds
[2025-06-19T01:31:35.056+0000] {processor.py:161} INFO - Started process (PID=52396) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:31:35.058+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:31:35.059+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:35.059+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:31:35.064+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:35.063+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:31:35.065+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:31:35.089+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.044 seconds
[2025-06-19T01:32:05.825+0000] {processor.py:161} INFO - Started process (PID=52432) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:32:05.829+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:32:05.831+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:05.830+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:32:05.835+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:05.834+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:32:05.836+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:32:05.857+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.042 seconds
[2025-06-19T01:32:36.485+0000] {processor.py:161} INFO - Started process (PID=52468) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:32:36.486+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:32:36.489+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:36.488+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:32:36.493+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:36.492+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:32:36.494+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:32:36.515+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.039 seconds
[2025-06-19T01:33:07.159+0000] {processor.py:161} INFO - Started process (PID=52504) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:33:07.161+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:33:07.163+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:07.162+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:33:07.167+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:07.166+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:33:07.168+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:33:07.190+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.042 seconds
[2025-06-19T01:33:37.849+0000] {processor.py:161} INFO - Started process (PID=52540) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:33:37.850+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:33:37.851+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:37.851+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:33:37.855+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:37.854+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:33:37.855+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:33:37.877+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.038 seconds
[2025-06-19T01:34:08.528+0000] {processor.py:161} INFO - Started process (PID=52576) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:34:08.530+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:34:08.532+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:08.531+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:34:08.537+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:08.536+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:34:08.538+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:34:08.571+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.053 seconds
[2025-06-19T01:34:39.311+0000] {processor.py:161} INFO - Started process (PID=52612) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:34:39.312+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:34:39.313+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:39.313+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:34:39.317+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:39.316+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:34:39.319+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:34:39.343+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.041 seconds
[2025-06-19T01:35:10.008+0000] {processor.py:161} INFO - Started process (PID=52649) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:35:10.009+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:35:10.010+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:10.010+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:35:10.013+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:10.013+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:35:10.014+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:35:10.035+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.036 seconds
[2025-06-19T01:35:40.797+0000] {processor.py:161} INFO - Started process (PID=52685) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:35:40.799+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:35:40.801+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:40.800+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:35:40.805+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:40.804+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:35:40.807+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:35:40.831+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.043 seconds
[2025-06-19T01:36:11.635+0000] {processor.py:161} INFO - Started process (PID=52721) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:36:11.636+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:36:11.638+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:11.638+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:36:11.642+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:11.641+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:36:11.643+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:36:11.665+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.041 seconds
[2025-06-19T01:36:42.485+0000] {processor.py:161} INFO - Started process (PID=52757) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:36:42.486+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:36:42.488+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:42.487+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:36:42.491+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:42.490+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:36:42.492+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:36:42.513+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.038 seconds
[2025-06-19T01:37:13.102+0000] {processor.py:161} INFO - Started process (PID=52793) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:37:13.104+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:37:13.105+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:13.104+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:37:13.109+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:13.108+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:37:13.110+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:37:13.137+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.044 seconds
[2025-06-19T01:37:43.754+0000] {processor.py:161} INFO - Started process (PID=52829) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:37:43.755+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:37:43.757+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:43.756+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:37:43.761+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:43.760+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:37:43.762+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:37:43.786+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.043 seconds
[2025-06-19T01:38:14.596+0000] {processor.py:161} INFO - Started process (PID=52865) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:38:14.597+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:38:14.599+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:14.599+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:38:14.602+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:14.602+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:38:14.603+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:38:14.623+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.036 seconds
[2025-06-19T01:38:45.223+0000] {processor.py:161} INFO - Started process (PID=52902) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:38:45.224+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:38:45.226+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:45.225+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:38:45.230+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:45.228+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:38:45.231+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:38:45.250+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.037 seconds
[2025-06-19T01:39:15.973+0000] {processor.py:161} INFO - Started process (PID=52938) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:39:15.974+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:39:15.975+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:15.975+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:39:15.979+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:15.977+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:39:15.980+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:39:16.000+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.037 seconds
[2025-06-19T01:39:46.456+0000] {processor.py:161} INFO - Started process (PID=52974) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:39:46.457+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:39:46.458+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:46.458+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:39:46.463+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:46.461+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:39:46.466+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:39:46.485+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.040 seconds
[2025-06-19T01:40:17.150+0000] {processor.py:161} INFO - Started process (PID=53010) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:40:17.151+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:40:17.152+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:17.152+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:40:17.156+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:17.155+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:40:17.158+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:40:17.183+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.045 seconds
[2025-06-19T01:40:47.839+0000] {processor.py:161} INFO - Started process (PID=53046) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:40:47.840+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:40:47.841+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:47.841+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:40:47.846+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:47.844+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:40:47.847+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:40:47.868+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.038 seconds
[2025-06-19T01:41:18.453+0000] {processor.py:161} INFO - Started process (PID=53082) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:41:18.454+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:41:18.456+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:18.455+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:41:18.462+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:18.461+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:41:18.464+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:41:18.496+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.059 seconds
[2025-06-19T01:41:49.265+0000] {processor.py:161} INFO - Started process (PID=53118) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:41:49.267+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:41:49.268+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:49.268+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:41:49.272+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:49.271+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:41:49.273+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:41:49.297+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.043 seconds
[2025-06-19T01:42:20.095+0000] {processor.py:161} INFO - Started process (PID=53155) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:42:20.097+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:42:20.098+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:20.098+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:42:20.103+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:20.102+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:42:20.104+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:42:20.126+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.043 seconds
[2025-06-19T01:42:50.637+0000] {processor.py:161} INFO - Started process (PID=53191) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:42:50.646+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:42:50.666+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:50.665+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:42:50.682+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:50.680+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:42:50.690+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:42:50.726+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.102 seconds
[2025-06-19T01:43:20.996+0000] {processor.py:161} INFO - Started process (PID=53227) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:43:20.998+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:43:21.000+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:20.999+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:43:21.005+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:21.004+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:43:21.006+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:43:21.038+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.057 seconds
[2025-06-19T01:43:51.321+0000] {processor.py:161} INFO - Started process (PID=53263) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:43:51.322+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:43:51.324+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:51.323+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:43:51.328+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:51.327+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:43:51.330+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:43:51.357+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.048 seconds
[2025-06-19T01:44:21.521+0000] {processor.py:161} INFO - Started process (PID=53300) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:44:21.523+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:44:21.525+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:21.524+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:44:21.529+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:21.528+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:44:21.530+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:44:21.553+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.043 seconds
[2025-06-19T01:44:51.916+0000] {processor.py:161} INFO - Started process (PID=53335) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:44:51.917+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:44:51.919+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:51.919+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:44:51.923+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:51.922+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:44:51.924+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:44:51.950+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.044 seconds
[2025-06-19T01:45:22.270+0000] {processor.py:161} INFO - Started process (PID=53372) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:45:22.271+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:45:22.272+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:22.272+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:45:22.277+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:22.276+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:45:22.279+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:45:22.312+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.056 seconds
[2025-06-19T01:45:52.913+0000] {processor.py:161} INFO - Started process (PID=53414) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:45:52.914+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:45:52.917+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:52.916+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:45:52.923+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:52.922+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:45:52.924+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:45:52.959+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.063 seconds
[2025-06-19T01:46:23.535+0000] {processor.py:161} INFO - Started process (PID=53450) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:46:23.537+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:46:23.539+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:23.538+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:46:23.544+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:23.543+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:46:23.545+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:46:23.577+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.056 seconds
[2025-06-19T01:46:53.824+0000] {processor.py:161} INFO - Started process (PID=53486) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:46:53.826+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:46:53.828+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:53.827+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:46:53.834+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:53.831+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:46:53.836+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:46:53.862+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.050 seconds
[2025-06-19T01:47:24.480+0000] {processor.py:161} INFO - Started process (PID=53522) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:47:24.481+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:47:24.482+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:24.482+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:47:24.487+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:24.486+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:47:24.489+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:47:24.512+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.043 seconds
[2025-06-19T01:47:54.675+0000] {processor.py:161} INFO - Started process (PID=53558) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:47:54.677+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:47:54.680+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:54.679+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:47:54.686+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:54.685+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:47:54.688+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:47:54.720+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.059 seconds
[2025-06-19T01:48:25.088+0000] {processor.py:161} INFO - Started process (PID=53594) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:48:25.089+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:48:25.091+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:25.090+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:48:25.095+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:25.094+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:48:25.096+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:48:25.123+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.045 seconds
[2025-06-19T01:48:55.275+0000] {processor.py:161} INFO - Started process (PID=53630) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:48:55.280+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:48:55.291+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:55.291+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:48:55.303+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:55.302+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:48:55.306+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:48:55.341+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.081 seconds
[2025-06-19T01:49:25.743+0000] {processor.py:161} INFO - Started process (PID=53666) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:49:25.745+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:49:25.748+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:25.747+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:49:25.753+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:25.752+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:49:25.755+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:49:25.787+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.057 seconds
[2025-06-19T01:49:56.138+0000] {processor.py:161} INFO - Started process (PID=53702) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:49:56.140+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:49:56.143+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:56.143+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:49:56.148+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:56.147+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:49:56.150+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:49:56.185+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.060 seconds
[2025-06-19T01:50:26.415+0000] {processor.py:161} INFO - Started process (PID=53738) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:50:26.417+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:50:26.419+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:26.418+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:50:26.423+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:26.422+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:50:26.424+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:50:26.451+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.046 seconds
[2025-06-19T01:50:56.751+0000] {processor.py:161} INFO - Started process (PID=53774) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:50:56.753+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:50:56.755+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:56.755+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:50:56.762+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:56.760+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:50:56.763+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:50:56.792+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.052 seconds
[2025-06-19T01:51:27.332+0000] {processor.py:161} INFO - Started process (PID=53811) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:51:27.334+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:51:27.336+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:27.336+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:51:27.341+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:27.340+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:51:27.342+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:51:27.367+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.045 seconds
[2025-06-19T01:51:57.989+0000] {processor.py:161} INFO - Started process (PID=53847) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:51:57.991+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:51:57.993+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:57.992+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:51:57.999+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:57.997+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:51:58.000+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:51:58.030+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.051 seconds
[2025-06-19T01:52:28.747+0000] {processor.py:161} INFO - Started process (PID=53883) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:52:28.748+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:52:28.751+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:28.749+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:52:28.758+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:28.757+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:52:28.760+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:52:28.800+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.070 seconds
[2025-06-19T01:52:59.128+0000] {processor.py:161} INFO - Started process (PID=53919) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:52:59.130+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:52:59.131+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:59.131+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:52:59.136+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:59.135+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:52:59.137+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:52:59.161+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.046 seconds
[2025-06-19T01:53:29.454+0000] {processor.py:161} INFO - Started process (PID=53955) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:53:29.455+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:53:29.456+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:29.456+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:53:29.460+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:29.459+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:53:29.461+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:53:29.479+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.034 seconds
[2025-06-19T01:53:59.665+0000] {processor.py:161} INFO - Started process (PID=53992) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:53:59.666+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:53:59.667+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:59.667+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:53:59.671+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:59.670+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:53:59.672+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:53:59.692+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.036 seconds
[2025-06-19T01:54:30.049+0000] {processor.py:161} INFO - Started process (PID=54028) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:54:30.051+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:54:30.052+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:30.052+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:54:30.056+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:30.055+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:54:30.058+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:54:30.079+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.039 seconds
[2025-06-19T01:55:00.451+0000] {processor.py:161} INFO - Started process (PID=54064) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:55:00.452+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:55:00.453+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:00.453+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:55:00.457+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:00.456+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:55:00.459+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:55:00.479+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.037 seconds
[2025-06-19T01:55:30.864+0000] {processor.py:161} INFO - Started process (PID=54100) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:55:30.866+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:55:30.868+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:30.867+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:55:30.873+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:30.872+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:55:30.874+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:55:30.896+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.044 seconds
[2025-06-19T01:56:01.037+0000] {processor.py:161} INFO - Started process (PID=54136) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:56:01.038+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:56:01.040+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:01.040+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:56:01.045+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:01.044+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:56:01.047+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:56:01.072+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.056 seconds
[2025-06-19T01:56:31.420+0000] {processor.py:161} INFO - Started process (PID=54172) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:56:31.421+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:56:31.423+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:31.423+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:56:31.428+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:31.427+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:56:31.430+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:56:31.454+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.047 seconds
[2025-06-19T01:57:01.691+0000] {processor.py:161} INFO - Started process (PID=54208) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:57:01.693+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:57:01.694+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:01.694+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:57:01.697+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:01.697+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:57:01.698+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:57:01.718+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.037 seconds
[2025-06-19T01:57:32.097+0000] {processor.py:161} INFO - Started process (PID=54244) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:57:32.100+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:57:32.102+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:32.101+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:57:32.107+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:32.106+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:57:32.111+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:57:32.130+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.043 seconds
[2025-06-19T01:58:02.557+0000] {processor.py:161} INFO - Started process (PID=54280) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:58:02.558+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:58:02.559+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:02.559+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:58:02.562+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:02.562+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:58:02.563+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:58:02.582+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.034 seconds
[2025-06-19T01:58:32.920+0000] {processor.py:161} INFO - Started process (PID=54316) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:58:32.921+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:58:32.923+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:32.922+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:58:32.927+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:32.926+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:58:32.928+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:58:32.948+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.037 seconds
[2025-06-19T01:59:03.235+0000] {processor.py:161} INFO - Started process (PID=54352) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:59:03.236+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:59:03.237+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:03.237+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:59:03.241+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:03.240+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:59:03.242+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:59:03.260+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.034 seconds
[2025-06-19T01:59:33.757+0000] {processor.py:161} INFO - Started process (PID=54388) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:59:33.758+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T01:59:33.760+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:33.760+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:59:33.764+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:33.763+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:59:33.765+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T01:59:33.788+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.041 seconds
[2025-06-19T02:00:04.004+0000] {processor.py:161} INFO - Started process (PID=54424) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T02:00:04.005+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T02:00:04.006+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:04.006+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T02:00:04.009+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:04.008+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T02:00:04.010+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T02:00:04.026+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.031 seconds
[2025-06-19T02:00:34.321+0000] {processor.py:161} INFO - Started process (PID=54460) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T02:00:34.322+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py for tasks to queue
[2025-06-19T02:00:34.324+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:34.323+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T02:00:34.327+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:34.326+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T02:00:34.328+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py
[2025-06-19T02:00:34.345+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_operator.py took 0.032 seconds
