[2025-06-19T01:17:19.113+0000] {processor.py:161} INFO - Started process (PID=51393) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:17:19.115+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:17:19.115+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:19.115+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:17:19.118+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:19.117+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:17:19.119+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:17:19.134+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.029 seconds
[2025-06-19T01:17:49.703+0000] {processor.py:161} INFO - Started process (PID=51429) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:17:49.704+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:17:49.706+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:49.705+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:17:49.709+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:49.708+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:17:49.709+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:17:49.724+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.028 seconds
[2025-06-19T01:18:20.136+0000] {processor.py:161} INFO - Started process (PID=51465) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:18:20.137+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:18:20.138+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:20.138+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:18:20.140+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:20.140+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:18:20.141+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:18:20.156+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.027 seconds
[2025-06-19T01:18:50.878+0000] {processor.py:161} INFO - Started process (PID=51501) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:18:50.880+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:18:50.881+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:50.881+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:18:50.884+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:50.883+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:18:50.885+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:18:50.912+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.041 seconds
[2025-06-19T01:19:21.579+0000] {processor.py:161} INFO - Started process (PID=51543) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:19:21.581+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:19:21.582+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:21.581+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:19:21.584+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:21.584+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:19:21.585+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:19:21.599+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.027 seconds
[2025-06-19T01:19:52.161+0000] {processor.py:161} INFO - Started process (PID=51579) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:19:52.163+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:19:52.164+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:52.164+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:19:52.167+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:52.166+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:19:52.167+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:19:52.186+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.033 seconds
[2025-06-19T01:20:22.603+0000] {processor.py:161} INFO - Started process (PID=51615) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:20:22.605+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:20:22.605+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:22.605+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:20:22.608+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:22.607+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:20:22.609+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:20:22.625+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.030 seconds
[2025-06-19T01:20:53.035+0000] {processor.py:161} INFO - Started process (PID=51651) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:20:53.036+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:20:53.037+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:53.036+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:20:53.040+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:53.039+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:20:53.040+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:20:53.055+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.028 seconds
[2025-06-19T01:21:23.793+0000] {processor.py:161} INFO - Started process (PID=51687) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:21:23.794+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:21:23.796+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:23.795+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:21:23.799+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:23.798+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:21:23.800+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:21:23.815+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.031 seconds
[2025-06-19T01:21:54.508+0000] {processor.py:161} INFO - Started process (PID=51723) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:21:54.508+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:21:54.509+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:54.509+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:21:54.512+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:54.511+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:21:54.513+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:21:54.527+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.026 seconds
[2025-06-19T01:22:25.008+0000] {processor.py:161} INFO - Started process (PID=51759) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:22:25.009+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:22:25.011+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:25.010+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:22:25.013+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:25.013+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:22:25.014+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:22:25.028+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.027 seconds
[2025-06-19T01:22:55.775+0000] {processor.py:161} INFO - Started process (PID=51795) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:22:55.776+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:22:55.778+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:55.777+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:22:55.781+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:55.780+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:22:55.782+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:22:55.798+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.032 seconds
[2025-06-19T01:23:26.427+0000] {processor.py:161} INFO - Started process (PID=51831) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:23:26.428+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:23:26.429+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:26.429+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:23:26.432+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:26.431+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:23:26.432+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:23:26.446+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.025 seconds
[2025-06-19T01:23:57.050+0000] {processor.py:161} INFO - Started process (PID=51867) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:23:57.051+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:23:57.052+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:57.052+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:23:57.055+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:57.054+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:23:57.055+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:23:57.071+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.029 seconds
[2025-06-19T01:24:27.673+0000] {processor.py:161} INFO - Started process (PID=51903) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:24:27.674+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:24:27.675+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:27.675+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:24:27.678+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:27.677+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:24:27.679+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:24:27.693+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.027 seconds
[2025-06-19T01:24:58.144+0000] {processor.py:161} INFO - Started process (PID=51938) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:24:58.146+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:24:58.147+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:58.147+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:24:58.150+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:58.149+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:24:58.151+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:24:58.165+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.028 seconds
[2025-06-19T01:25:28.807+0000] {processor.py:161} INFO - Started process (PID=51975) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:25:28.808+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:25:28.809+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:28.809+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:25:28.812+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:28.811+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:25:28.814+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:25:28.834+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.034 seconds
[2025-06-19T01:25:59.407+0000] {processor.py:161} INFO - Started process (PID=52011) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:25:59.408+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:25:59.409+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:59.408+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:25:59.411+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:59.410+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:25:59.411+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:25:59.427+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.028 seconds
[2025-06-19T01:26:30.261+0000] {processor.py:161} INFO - Started process (PID=52047) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:26:30.262+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:26:30.263+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:26:30.263+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:26:30.266+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:26:30.265+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:26:30.267+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:26:30.285+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.035 seconds
[2025-06-19T01:27:00.701+0000] {processor.py:161} INFO - Started process (PID=52083) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:27:00.702+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:27:00.703+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:00.703+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:27:00.706+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:00.705+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:27:00.706+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:27:00.722+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.031 seconds
[2025-06-19T01:27:31.213+0000] {processor.py:161} INFO - Started process (PID=52119) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:27:31.214+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:27:31.214+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:31.214+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:27:31.217+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:31.217+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:27:31.218+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:27:31.233+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.029 seconds
[2025-06-19T01:28:01.828+0000] {processor.py:161} INFO - Started process (PID=52155) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:28:01.829+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:28:01.831+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:01.831+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:28:01.835+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:01.834+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:28:01.837+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:28:01.856+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.038 seconds
[2025-06-19T01:28:32.544+0000] {processor.py:161} INFO - Started process (PID=52191) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:28:32.545+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:28:32.546+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:32.546+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:28:32.550+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:32.549+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:28:32.550+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:28:32.569+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.034 seconds
[2025-06-19T01:29:03.327+0000] {processor.py:161} INFO - Started process (PID=52227) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:29:03.329+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:29:03.330+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:03.329+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:29:03.333+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:03.332+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:29:03.334+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:29:03.361+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.044 seconds
[2025-06-19T01:29:33.548+0000] {processor.py:161} INFO - Started process (PID=52263) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:29:33.549+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:29:33.550+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:33.550+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:29:33.553+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:33.553+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:29:33.554+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:29:33.574+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.037 seconds
[2025-06-19T01:30:03.739+0000] {processor.py:161} INFO - Started process (PID=52299) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:30:03.740+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:30:03.743+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:03.741+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:30:03.748+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:03.747+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:30:03.749+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:30:03.772+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.042 seconds
[2025-06-19T01:30:34.417+0000] {processor.py:161} INFO - Started process (PID=52335) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:30:34.418+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:30:34.419+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:34.419+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:30:34.423+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:34.422+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:30:34.424+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:30:34.441+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.034 seconds
[2025-06-19T01:31:04.971+0000] {processor.py:161} INFO - Started process (PID=52371) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:31:04.973+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:31:04.974+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:04.974+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:31:04.978+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:04.977+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:31:04.979+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:31:05.003+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.041 seconds
[2025-06-19T01:31:35.676+0000] {processor.py:161} INFO - Started process (PID=52407) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:31:35.678+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:31:35.680+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:35.679+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:31:35.685+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:35.684+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:31:35.686+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:31:35.709+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.045 seconds
[2025-06-19T01:32:06.313+0000] {processor.py:161} INFO - Started process (PID=52443) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:32:06.314+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:32:06.316+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:06.315+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:32:06.321+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:06.319+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:32:06.322+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:32:06.344+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.041 seconds
[2025-06-19T01:32:37.042+0000] {processor.py:161} INFO - Started process (PID=52479) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:32:37.043+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:32:37.045+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:37.044+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:32:37.049+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:37.048+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:32:37.051+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:32:37.071+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.039 seconds
[2025-06-19T01:33:07.735+0000] {processor.py:161} INFO - Started process (PID=52515) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:33:07.736+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:33:07.738+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:07.737+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:33:07.742+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:07.741+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:33:07.743+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:33:07.764+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.040 seconds
[2025-06-19T01:33:38.428+0000] {processor.py:161} INFO - Started process (PID=52551) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:33:38.429+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:33:38.431+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:38.430+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:33:38.435+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:38.434+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:33:38.437+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:33:38.457+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.038 seconds
[2025-06-19T01:34:09.089+0000] {processor.py:161} INFO - Started process (PID=52587) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:34:09.091+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:34:09.092+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:09.092+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:34:09.097+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:09.096+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:34:09.098+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:34:09.123+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.046 seconds
[2025-06-19T01:34:39.897+0000] {processor.py:161} INFO - Started process (PID=52623) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:34:39.899+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:34:39.901+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:39.900+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:34:39.905+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:39.904+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:34:39.906+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:34:39.931+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.045 seconds
[2025-06-19T01:35:10.569+0000] {processor.py:161} INFO - Started process (PID=52660) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:35:10.571+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:35:10.572+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:10.572+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:35:10.577+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:10.576+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:35:10.578+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:35:10.598+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.040 seconds
[2025-06-19T01:35:41.449+0000] {processor.py:161} INFO - Started process (PID=52696) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:35:41.451+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:35:41.452+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:41.452+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:35:41.457+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:41.456+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:35:41.458+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:35:41.481+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.042 seconds
[2025-06-19T01:36:12.261+0000] {processor.py:161} INFO - Started process (PID=52732) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:36:12.263+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:36:12.264+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:12.264+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:36:12.268+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:12.267+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:36:12.269+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:36:12.293+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.045 seconds
[2025-06-19T01:36:43.063+0000] {processor.py:161} INFO - Started process (PID=52768) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:36:43.064+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:36:43.066+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:43.066+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:36:43.071+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:43.069+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:36:43.072+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:36:43.094+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.041 seconds
[2025-06-19T01:37:13.618+0000] {processor.py:161} INFO - Started process (PID=52804) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:37:13.620+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:37:13.621+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:13.620+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:37:13.624+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:13.623+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:37:13.625+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:37:13.646+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.038 seconds
[2025-06-19T01:37:44.439+0000] {processor.py:161} INFO - Started process (PID=52840) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:37:44.441+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:37:44.443+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:44.442+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:37:44.448+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:44.446+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:37:44.449+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:37:44.472+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.044 seconds
[2025-06-19T01:38:15.183+0000] {processor.py:161} INFO - Started process (PID=52876) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:38:15.185+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:38:15.187+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:15.186+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:38:15.190+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:15.189+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:38:15.191+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:38:15.211+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.039 seconds
[2025-06-19T01:38:45.804+0000] {processor.py:161} INFO - Started process (PID=52913) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:38:45.806+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:38:45.807+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:45.807+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:38:45.811+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:45.810+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:38:45.812+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:38:45.832+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.038 seconds
[2025-06-19T01:39:16.436+0000] {processor.py:161} INFO - Started process (PID=52949) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:39:16.438+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:39:16.438+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:16.438+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:39:16.441+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:16.441+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:39:16.442+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:39:16.462+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.036 seconds
[2025-06-19T01:39:47.044+0000] {processor.py:161} INFO - Started process (PID=52985) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:39:47.045+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:39:47.047+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:47.046+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:39:47.051+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:47.050+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:39:47.052+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:39:47.074+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.039 seconds
[2025-06-19T01:40:17.783+0000] {processor.py:161} INFO - Started process (PID=53022) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:40:17.785+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:40:17.786+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:17.786+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:40:17.790+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:17.789+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:40:17.790+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:40:17.812+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.040 seconds
[2025-06-19T01:40:48.415+0000] {processor.py:161} INFO - Started process (PID=53058) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:40:48.416+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:40:48.417+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:48.416+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:40:48.421+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:48.420+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:40:48.423+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:40:48.443+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.038 seconds
[2025-06-19T01:41:19.100+0000] {processor.py:161} INFO - Started process (PID=53093) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:41:19.101+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:41:19.103+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:19.102+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:41:19.107+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:19.106+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:41:19.108+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:41:19.129+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.042 seconds
[2025-06-19T01:41:49.890+0000] {processor.py:161} INFO - Started process (PID=53129) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:41:49.891+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:41:49.893+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:49.892+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:41:49.896+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:49.895+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:41:49.898+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:41:49.920+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.041 seconds
[2025-06-19T01:42:20.916+0000] {processor.py:161} INFO - Started process (PID=53166) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:42:20.917+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:42:20.919+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:20.919+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:42:20.924+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:20.923+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:42:20.925+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:42:20.948+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.044 seconds
[2025-06-19T01:42:52.959+0000] {processor.py:161} INFO - Started process (PID=53208) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:42:52.961+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:42:52.962+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:52.962+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:42:52.967+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:52.966+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:42:52.968+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:42:52.993+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.047 seconds
[2025-06-19T01:43:23.688+0000] {processor.py:161} INFO - Started process (PID=53244) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:43:23.689+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:43:23.690+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:23.690+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:43:23.696+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:23.694+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:43:23.698+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:43:23.723+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.046 seconds
[2025-06-19T01:43:53.869+0000] {processor.py:161} INFO - Started process (PID=53280) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:43:53.870+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:43:53.872+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:53.871+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:43:53.876+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:53.875+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:43:53.877+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:43:53.905+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.048 seconds
[2025-06-19T01:44:24.071+0000] {processor.py:161} INFO - Started process (PID=53316) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:44:24.073+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:44:24.075+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:24.074+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:44:24.079+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:24.078+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:44:24.080+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:44:24.108+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.051 seconds
[2025-06-19T01:44:54.427+0000] {processor.py:161} INFO - Started process (PID=53353) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:44:54.429+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:44:54.430+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:54.430+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:44:54.434+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:54.433+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:44:54.436+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:44:54.461+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.049 seconds
[2025-06-19T01:45:24.818+0000] {processor.py:161} INFO - Started process (PID=53389) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:45:24.819+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:45:24.821+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:24.820+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:45:24.826+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:24.824+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:45:24.828+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:45:24.859+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.052 seconds
[2025-06-19T01:45:55.498+0000] {processor.py:161} INFO - Started process (PID=53425) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:45:55.499+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:45:55.501+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:55.501+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:45:55.507+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:55.506+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:45:55.509+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:45:55.544+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.063 seconds
[2025-06-19T01:46:26.195+0000] {processor.py:161} INFO - Started process (PID=53461) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:46:26.197+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:46:26.199+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:26.199+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:46:26.206+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:26.204+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:46:26.208+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:46:26.243+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.064 seconds
[2025-06-19T01:46:56.366+0000] {processor.py:161} INFO - Started process (PID=53497) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:46:56.368+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:46:56.370+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:56.370+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:46:56.375+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:56.374+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:46:56.376+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:46:56.401+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.047 seconds
[2025-06-19T01:47:27.036+0000] {processor.py:161} INFO - Started process (PID=53533) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:47:27.037+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:47:27.039+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:27.039+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:47:27.044+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:27.043+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:47:27.045+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:47:27.074+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.053 seconds
[2025-06-19T01:47:57.399+0000] {processor.py:161} INFO - Started process (PID=53569) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:47:57.401+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:47:57.403+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:57.402+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:47:57.410+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:57.408+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:47:57.412+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:47:57.443+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.057 seconds
[2025-06-19T01:48:27.665+0000] {processor.py:161} INFO - Started process (PID=53605) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:48:27.667+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:48:27.669+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:27.668+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:48:27.673+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:27.672+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:48:27.674+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:48:27.703+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.051 seconds
[2025-06-19T01:48:58.064+0000] {processor.py:161} INFO - Started process (PID=53641) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:48:58.065+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:48:58.066+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:58.065+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:48:58.069+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:58.068+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:48:58.071+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:48:58.096+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.045 seconds
[2025-06-19T01:49:28.533+0000] {processor.py:161} INFO - Started process (PID=53677) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:49:28.535+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:49:28.538+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:28.537+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:49:28.543+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:28.541+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:49:28.546+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:49:28.578+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.060 seconds
[2025-06-19T01:49:58.692+0000] {processor.py:161} INFO - Started process (PID=53713) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:49:58.694+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:49:58.695+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:58.694+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:49:58.700+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:58.699+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:49:58.701+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:49:58.726+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.046 seconds
[2025-06-19T01:50:29.045+0000] {processor.py:161} INFO - Started process (PID=53749) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:50:29.047+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:50:29.049+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:29.048+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:50:29.056+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:29.054+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:50:29.060+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:50:29.097+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.073 seconds
[2025-06-19T01:50:59.238+0000] {processor.py:161} INFO - Started process (PID=53785) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:50:59.239+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:50:59.240+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:59.240+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:50:59.244+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:59.243+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:50:59.245+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:50:59.266+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.039 seconds
[2025-06-19T01:51:29.862+0000] {processor.py:161} INFO - Started process (PID=53822) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:51:29.864+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:51:29.865+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:29.865+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:51:29.871+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:29.870+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:51:29.872+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:51:29.896+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.046 seconds
[2025-06-19T01:52:00.583+0000] {processor.py:161} INFO - Started process (PID=53858) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:52:00.587+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:52:00.589+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:00.588+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:52:00.595+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:00.593+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:52:00.596+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:52:00.623+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.054 seconds
[2025-06-19T01:52:32.108+0000] {processor.py:161} INFO - Started process (PID=53894) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:52:32.110+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:52:32.111+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:32.110+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:52:32.114+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:32.113+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:52:32.115+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:52:32.138+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.041 seconds
[2025-06-19T01:53:02.562+0000] {processor.py:161} INFO - Started process (PID=53930) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:53:02.563+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:53:02.564+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:02.563+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:53:02.568+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:02.566+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:53:02.569+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:53:02.590+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.048 seconds
[2025-06-19T01:53:32.805+0000] {processor.py:161} INFO - Started process (PID=53966) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:53:32.807+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:53:32.808+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:32.807+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:53:32.811+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:32.810+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:53:32.812+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:53:32.830+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.034 seconds
[2025-06-19T01:54:03.059+0000] {processor.py:161} INFO - Started process (PID=54003) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:54:03.060+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:54:03.061+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:03.061+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:54:03.064+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:03.063+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:54:03.065+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:54:03.087+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.038 seconds
[2025-06-19T01:54:33.447+0000] {processor.py:161} INFO - Started process (PID=54039) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:54:33.449+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:54:33.450+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:33.450+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:54:33.454+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:33.453+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:54:33.455+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:54:33.475+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.039 seconds
[2025-06-19T01:55:03.831+0000] {processor.py:161} INFO - Started process (PID=54075) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:55:03.834+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:55:03.837+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:03.836+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:55:03.842+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:03.842+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:55:03.847+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:55:03.869+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.046 seconds
[2025-06-19T01:55:34.152+0000] {processor.py:161} INFO - Started process (PID=54111) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:55:34.153+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:55:34.154+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:34.154+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:55:34.158+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:34.157+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:55:34.159+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:55:34.180+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.037 seconds
[2025-06-19T01:56:04.471+0000] {processor.py:161} INFO - Started process (PID=54147) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:56:04.472+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:56:04.474+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:04.473+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:56:04.477+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:04.476+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:56:04.478+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:56:04.498+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.037 seconds
[2025-06-19T01:56:34.770+0000] {processor.py:161} INFO - Started process (PID=54183) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:56:34.772+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:56:34.773+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:34.773+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:56:34.777+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:34.776+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:56:34.779+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:56:34.797+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.037 seconds
[2025-06-19T01:57:05.069+0000] {processor.py:161} INFO - Started process (PID=54219) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:57:05.070+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:57:05.071+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:05.070+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:57:05.073+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:05.072+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:57:05.074+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:57:05.093+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.033 seconds
[2025-06-19T01:57:35.529+0000] {processor.py:161} INFO - Started process (PID=54255) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:57:35.530+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:57:35.531+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:35.531+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:57:35.535+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:35.534+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:57:35.535+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:57:35.555+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.035 seconds
[2025-06-19T01:58:05.967+0000] {processor.py:161} INFO - Started process (PID=54291) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:58:05.968+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:58:05.970+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:05.969+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:58:05.974+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:05.973+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:58:05.975+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:58:05.997+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.042 seconds
[2025-06-19T01:58:36.344+0000] {processor.py:161} INFO - Started process (PID=54327) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:58:36.345+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:58:36.347+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:36.346+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:58:36.351+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:36.350+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:58:36.352+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:58:36.370+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.036 seconds
[2025-06-19T01:59:06.663+0000] {processor.py:161} INFO - Started process (PID=54363) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:59:06.664+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:59:06.665+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:06.665+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:59:06.669+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:06.668+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:59:06.670+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:59:06.690+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.038 seconds
[2025-06-19T01:59:37.144+0000] {processor.py:161} INFO - Started process (PID=54399) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:59:37.146+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T01:59:37.147+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:37.147+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:59:37.151+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:37.149+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:59:37.152+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T01:59:37.171+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.037 seconds
[2025-06-19T02:00:07.466+0000] {processor.py:161} INFO - Started process (PID=54435) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T02:00:07.467+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T02:00:07.468+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:07.468+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T02:00:07.471+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:07.471+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T02:00:07.473+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T02:00:07.491+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.033 seconds
[2025-06-19T02:00:37.632+0000] {processor.py:161} INFO - Started process (PID=54471) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T02:00:37.633+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py for tasks to queue
[2025-06-19T02:00:37.635+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:37.634+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T02:00:37.638+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:37.637+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py", line 23, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T02:00:37.639+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py
[2025-06-19T02:00:37.655+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_bash_decorator.py took 0.030 seconds
