[2025-06-19T01:17:19.401+0000] {processor.py:161} INFO - Started process (PID=51399) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:17:19.402+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:17:19.403+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:19.403+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:17:19.406+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:19.405+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:17:19.407+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:17:19.421+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.028 seconds
[2025-06-19T01:17:49.970+0000] {processor.py:161} INFO - Started process (PID=51435) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:17:49.971+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:17:49.973+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:49.972+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:17:49.975+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:49.974+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:17:49.975+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:17:49.990+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.029 seconds
[2025-06-19T01:18:20.421+0000] {processor.py:161} INFO - Started process (PID=51471) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:18:20.422+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:18:20.423+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:20.423+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:18:20.425+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:20.425+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:18:20.426+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:18:20.440+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.027 seconds
[2025-06-19T01:18:51.209+0000] {processor.py:161} INFO - Started process (PID=51513) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:18:51.210+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:18:51.210+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:51.210+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:18:51.215+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:51.214+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:18:51.216+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:18:51.232+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.031 seconds
[2025-06-19T01:19:21.851+0000] {processor.py:161} INFO - Started process (PID=51549) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:19:21.852+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:19:21.853+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:21.853+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:19:21.856+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:21.855+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:19:21.857+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:19:21.873+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.030 seconds
[2025-06-19T01:19:52.374+0000] {processor.py:161} INFO - Started process (PID=51585) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:19:52.375+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:19:52.376+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:52.376+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:19:52.378+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:52.378+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:19:52.379+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:19:52.393+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.027 seconds
[2025-06-19T01:20:22.799+0000] {processor.py:161} INFO - Started process (PID=51621) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:20:22.800+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:20:22.801+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:22.801+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:20:22.803+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:22.802+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:20:22.804+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:20:22.818+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.026 seconds
[2025-06-19T01:20:53.242+0000] {processor.py:161} INFO - Started process (PID=51657) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:20:53.245+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:20:53.246+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:53.246+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:20:53.248+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:53.248+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:20:53.249+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:20:53.268+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.034 seconds
[2025-06-19T01:21:24.103+0000] {processor.py:161} INFO - Started process (PID=51693) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:21:24.104+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:21:24.105+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:24.105+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:21:24.108+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:24.107+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:21:24.109+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:21:24.124+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.029 seconds
[2025-06-19T01:21:54.695+0000] {processor.py:161} INFO - Started process (PID=51729) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:21:54.697+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:21:54.698+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:54.697+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:21:54.700+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:54.699+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:21:54.701+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:21:54.714+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.026 seconds
[2025-06-19T01:22:25.278+0000] {processor.py:161} INFO - Started process (PID=51765) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:22:25.279+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:22:25.280+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:25.280+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:22:25.283+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:25.282+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:22:25.283+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:22:25.297+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.026 seconds
[2025-06-19T01:22:56.148+0000] {processor.py:161} INFO - Started process (PID=51801) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:22:56.150+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:22:56.151+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:56.150+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:22:56.153+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:56.152+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:22:56.154+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:22:56.168+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.029 seconds
[2025-06-19T01:23:26.632+0000] {processor.py:161} INFO - Started process (PID=51837) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:23:26.634+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:23:26.635+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:26.634+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:23:26.637+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:26.636+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:23:26.638+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:23:26.653+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.030 seconds
[2025-06-19T01:23:57.355+0000] {processor.py:161} INFO - Started process (PID=51873) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:23:57.356+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:23:57.357+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:57.357+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:23:57.361+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:57.359+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:23:57.361+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:23:57.376+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.029 seconds
[2025-06-19T01:24:27.942+0000] {processor.py:161} INFO - Started process (PID=51909) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:24:27.944+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:24:27.945+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:27.944+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:24:27.948+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:27.947+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:24:27.949+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:24:27.962+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.028 seconds
[2025-06-19T01:24:58.482+0000] {processor.py:161} INFO - Started process (PID=51945) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:24:58.483+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:24:58.484+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:58.484+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:24:58.487+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:58.486+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:24:58.488+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:24:58.503+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.034 seconds
[2025-06-19T01:25:29.121+0000] {processor.py:161} INFO - Started process (PID=51981) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:25:29.123+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:25:29.124+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:29.123+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:25:29.126+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:29.125+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:25:29.126+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:25:29.142+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.028 seconds
[2025-06-19T01:25:59.694+0000] {processor.py:161} INFO - Started process (PID=52017) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:25:59.695+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:25:59.696+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:59.696+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:25:59.699+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:59.698+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:25:59.700+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:25:59.716+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.029 seconds
[2025-06-19T01:26:30.509+0000] {processor.py:161} INFO - Started process (PID=52053) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:26:30.511+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:26:30.512+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:26:30.512+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:26:30.515+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:26:30.514+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:26:30.515+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:26:30.533+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.034 seconds
[2025-06-19T01:27:00.895+0000] {processor.py:161} INFO - Started process (PID=52089) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:27:00.896+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:27:00.896+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:00.896+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:27:00.900+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:00.899+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:27:00.901+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:27:00.916+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.030 seconds
[2025-06-19T01:27:31.496+0000] {processor.py:161} INFO - Started process (PID=52125) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:27:31.497+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:27:31.498+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:31.498+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:27:31.501+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:31.500+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:27:31.502+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:27:31.519+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.032 seconds
[2025-06-19T01:28:02.129+0000] {processor.py:161} INFO - Started process (PID=52161) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:28:02.131+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:28:02.133+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:02.133+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:28:02.137+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:02.136+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:28:02.138+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:28:02.159+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.038 seconds
[2025-06-19T01:28:32.832+0000] {processor.py:161} INFO - Started process (PID=52197) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:28:32.833+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:28:32.834+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:32.834+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:28:32.837+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:32.837+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:28:32.838+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:28:32.857+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.033 seconds
[2025-06-19T01:29:03.823+0000] {processor.py:161} INFO - Started process (PID=52233) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:29:03.824+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:29:03.826+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:03.825+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:29:03.831+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:03.830+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:29:03.833+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:29:03.862+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.053 seconds
[2025-06-19T01:29:33.980+0000] {processor.py:161} INFO - Started process (PID=52269) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:29:33.982+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:29:33.983+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:33.982+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:29:33.986+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:33.985+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:29:33.987+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:29:34.008+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.038 seconds
[2025-06-19T01:30:04.084+0000] {processor.py:161} INFO - Started process (PID=52305) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:30:04.086+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:30:04.088+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:04.087+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:30:04.091+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:04.090+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:30:04.091+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:30:04.113+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.038 seconds
[2025-06-19T01:30:34.731+0000] {processor.py:161} INFO - Started process (PID=52341) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:30:34.732+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:30:34.733+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:34.733+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:30:34.736+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:34.735+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:30:34.737+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:30:34.756+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.035 seconds
[2025-06-19T01:31:05.295+0000] {processor.py:161} INFO - Started process (PID=52377) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:31:05.296+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:31:05.297+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:05.297+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:31:05.301+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:05.300+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:31:05.302+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:31:05.321+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.035 seconds
[2025-06-19T01:31:36.026+0000] {processor.py:161} INFO - Started process (PID=52413) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:31:36.028+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:31:36.029+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:36.029+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:31:36.034+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:36.032+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:31:36.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:31:36.060+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.046 seconds
[2025-06-19T01:32:06.652+0000] {processor.py:161} INFO - Started process (PID=52449) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:32:06.654+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:32:06.656+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:06.655+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:32:06.659+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:06.658+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:32:06.660+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:32:06.680+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.037 seconds
[2025-06-19T01:32:37.377+0000] {processor.py:161} INFO - Started process (PID=52485) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:32:37.378+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:32:37.379+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:37.379+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:32:37.382+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:37.381+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:32:37.383+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:32:37.405+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.039 seconds
[2025-06-19T01:33:08.053+0000] {processor.py:161} INFO - Started process (PID=52521) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:33:08.054+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:33:08.055+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:08.054+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:33:08.057+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:08.056+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:33:08.058+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:33:08.077+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.034 seconds
[2025-06-19T01:33:38.665+0000] {processor.py:161} INFO - Started process (PID=52557) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:33:38.667+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:33:38.667+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:38.667+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:33:38.670+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:38.669+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:33:38.672+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:33:38.694+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.040 seconds
[2025-06-19T01:34:09.478+0000] {processor.py:161} INFO - Started process (PID=52593) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:34:09.480+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:34:09.481+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:09.480+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:34:09.484+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:09.483+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:34:09.485+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:34:09.509+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.043 seconds
[2025-06-19T01:34:40.229+0000] {processor.py:161} INFO - Started process (PID=52629) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:34:40.233+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:34:40.235+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:40.234+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:34:40.238+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:40.237+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:34:40.239+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:34:40.261+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.043 seconds
[2025-06-19T01:35:10.902+0000] {processor.py:161} INFO - Started process (PID=52666) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:35:10.903+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:35:10.904+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:10.904+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:35:10.907+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:10.906+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:35:10.908+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:35:10.926+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.035 seconds
[2025-06-19T01:35:41.813+0000] {processor.py:161} INFO - Started process (PID=52702) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:35:41.814+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:35:41.816+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:41.816+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:35:41.820+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:41.818+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:35:41.821+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:35:41.843+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.042 seconds
[2025-06-19T01:36:12.628+0000] {processor.py:161} INFO - Started process (PID=52738) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:36:12.629+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:36:12.630+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:12.630+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:36:12.633+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:12.632+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:36:12.634+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:36:12.662+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.046 seconds
[2025-06-19T01:36:43.398+0000] {processor.py:161} INFO - Started process (PID=52774) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:36:43.399+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:36:43.401+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:43.400+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:36:43.405+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:43.403+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:36:43.406+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:36:43.426+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.038 seconds
[2025-06-19T01:37:13.879+0000] {processor.py:161} INFO - Started process (PID=52810) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:37:13.881+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:37:13.883+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:13.882+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:37:13.887+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:13.886+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:37:13.888+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:37:13.910+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.042 seconds
[2025-06-19T01:37:44.748+0000] {processor.py:161} INFO - Started process (PID=52846) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:37:44.749+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:37:44.751+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:44.750+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:37:44.754+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:44.753+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:37:44.755+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:37:44.784+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.049 seconds
[2025-06-19T01:38:15.439+0000] {processor.py:161} INFO - Started process (PID=52882) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:38:15.441+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:38:15.443+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:15.443+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:38:15.448+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:15.447+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:38:15.450+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:38:15.474+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.049 seconds
[2025-06-19T01:38:46.141+0000] {processor.py:161} INFO - Started process (PID=52919) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:38:46.143+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:38:46.145+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:46.144+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:38:46.149+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:46.148+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:38:46.150+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:38:46.171+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.041 seconds
[2025-06-19T01:39:16.762+0000] {processor.py:161} INFO - Started process (PID=52955) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:39:16.764+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:39:16.765+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:16.765+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:39:16.768+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:16.767+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:39:16.769+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:39:16.787+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.036 seconds
[2025-06-19T01:39:47.368+0000] {processor.py:161} INFO - Started process (PID=52991) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:39:47.369+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:39:47.370+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:47.370+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:39:47.374+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:47.373+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:39:47.375+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:39:47.396+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.038 seconds
[2025-06-19T01:40:18.035+0000] {processor.py:161} INFO - Started process (PID=53027) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:40:18.036+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:40:18.037+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:18.037+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:40:18.040+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:18.039+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:40:18.040+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:40:18.060+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.036 seconds
[2025-06-19T01:40:48.654+0000] {processor.py:161} INFO - Started process (PID=53063) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:40:48.656+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:40:48.657+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:48.657+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:40:48.661+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:48.660+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:40:48.662+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:40:48.684+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.041 seconds
[2025-06-19T01:41:19.382+0000] {processor.py:161} INFO - Started process (PID=53099) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:41:19.384+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:41:19.386+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:19.386+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:41:19.389+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:19.389+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:41:19.391+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:41:19.415+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.045 seconds
[2025-06-19T01:41:50.174+0000] {processor.py:161} INFO - Started process (PID=53135) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:41:50.176+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:41:50.177+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:50.177+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:41:50.181+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:50.180+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:41:50.182+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:41:50.207+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.045 seconds
[2025-06-19T01:42:21.317+0000] {processor.py:161} INFO - Started process (PID=53172) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:42:21.318+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:42:21.319+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:21.319+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:42:21.323+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:21.322+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:42:21.324+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:42:21.348+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.043 seconds
[2025-06-19T01:42:53.328+0000] {processor.py:161} INFO - Started process (PID=53214) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:42:53.329+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:42:53.330+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:53.330+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:42:53.336+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:53.334+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:42:53.337+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:42:53.361+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.045 seconds
[2025-06-19T01:43:23.994+0000] {processor.py:161} INFO - Started process (PID=53250) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:43:23.996+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:43:23.997+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:23.996+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:43:24.000+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:23.999+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:43:24.001+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:43:24.031+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.050 seconds
[2025-06-19T01:43:54.253+0000] {processor.py:161} INFO - Started process (PID=53286) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:43:54.255+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:43:54.257+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:54.257+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:43:54.261+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:54.259+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:43:54.263+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:43:54.288+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.046 seconds
[2025-06-19T01:44:24.485+0000] {processor.py:161} INFO - Started process (PID=53322) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:44:24.486+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:44:24.488+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:24.487+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:44:24.492+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:24.491+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:44:24.494+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:44:24.519+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.045 seconds
[2025-06-19T01:44:54.843+0000] {processor.py:161} INFO - Started process (PID=53359) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:44:54.845+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:44:54.848+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:54.847+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:44:54.853+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:54.852+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:44:54.855+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:44:54.886+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.059 seconds
[2025-06-19T01:45:25.249+0000] {processor.py:161} INFO - Started process (PID=53395) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:45:25.251+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:45:25.252+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:25.252+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:45:25.255+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:25.255+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:45:25.256+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:45:25.286+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.049 seconds
[2025-06-19T01:45:56.033+0000] {processor.py:161} INFO - Started process (PID=53431) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:45:56.034+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:45:56.036+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:56.036+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:45:56.045+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:56.042+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:45:56.048+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:45:56.080+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.066 seconds
[2025-06-19T01:46:27.770+0000] {processor.py:161} INFO - Started process (PID=53467) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:46:27.781+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:46:27.798+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:27.797+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:46:27.823+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:27.821+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:46:27.841+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:46:27.892+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.140 seconds
[2025-06-19T01:46:58.607+0000] {processor.py:161} INFO - Started process (PID=53503) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:46:58.609+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:46:58.610+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:58.610+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:46:58.614+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:58.613+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:46:58.615+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:46:58.655+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.059 seconds
[2025-06-19T01:47:29.311+0000] {processor.py:161} INFO - Started process (PID=53539) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:47:29.312+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:47:29.314+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:29.314+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:47:29.319+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:29.318+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:47:29.321+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:47:29.352+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.053 seconds
[2025-06-19T01:47:59.652+0000] {processor.py:161} INFO - Started process (PID=53575) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:47:59.653+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:47:59.655+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:59.655+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:47:59.659+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:59.658+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:47:59.660+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:47:59.690+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.054 seconds
[2025-06-19T01:48:29.957+0000] {processor.py:161} INFO - Started process (PID=53611) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:48:29.959+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:48:29.962+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:29.961+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:48:29.968+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:29.966+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:48:29.970+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:48:30.002+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.064 seconds
[2025-06-19T01:49:00.216+0000] {processor.py:161} INFO - Started process (PID=53647) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:49:00.218+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:49:00.221+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:00.220+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:49:00.225+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:00.223+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:49:00.226+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:49:00.251+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.046 seconds
[2025-06-19T01:49:30.715+0000] {processor.py:161} INFO - Started process (PID=53683) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:49:30.717+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:49:30.718+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:30.718+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:49:30.723+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:30.722+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:49:30.724+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:49:30.751+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.048 seconds
[2025-06-19T01:50:00.913+0000] {processor.py:161} INFO - Started process (PID=53719) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:50:00.914+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:50:00.916+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:00.915+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:50:00.921+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:00.920+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:50:00.922+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:50:00.946+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.045 seconds
[2025-06-19T01:50:31.322+0000] {processor.py:161} INFO - Started process (PID=53755) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:50:31.323+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:50:31.325+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:31.324+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:50:31.329+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:31.328+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:50:31.330+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:50:31.358+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.049 seconds
[2025-06-19T01:51:01.455+0000] {processor.py:161} INFO - Started process (PID=53791) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:51:01.457+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:51:01.458+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:01.457+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:51:01.462+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:01.461+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:51:01.463+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:51:01.481+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.037 seconds
[2025-06-19T01:51:32.078+0000] {processor.py:161} INFO - Started process (PID=53828) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:51:32.079+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:51:32.081+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:32.080+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:51:32.084+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:32.083+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:51:32.086+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:51:32.110+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.044 seconds
[2025-06-19T01:52:02.844+0000] {processor.py:161} INFO - Started process (PID=53864) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:52:02.846+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:52:02.848+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:02.848+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:52:02.852+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:02.852+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:52:02.853+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:52:02.876+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.043 seconds
[2025-06-19T01:52:33.313+0000] {processor.py:161} INFO - Started process (PID=53900) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:52:33.314+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:52:33.315+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:33.315+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:52:33.320+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:33.319+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:52:33.321+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:52:33.346+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.045 seconds
[2025-06-19T01:53:03.777+0000] {processor.py:161} INFO - Started process (PID=53936) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:53:03.779+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:53:03.780+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:03.780+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:53:03.784+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:03.783+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:53:03.785+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:53:03.806+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.039 seconds
[2025-06-19T01:53:33.978+0000] {processor.py:161} INFO - Started process (PID=53972) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:53:33.979+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:53:33.980+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:33.979+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:53:33.982+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:33.982+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:53:33.984+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:53:34.001+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.033 seconds
[2025-06-19T01:54:04.282+0000] {processor.py:161} INFO - Started process (PID=54009) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:54:04.287+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:54:04.290+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:04.289+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:54:04.297+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:04.296+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:54:04.299+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:54:04.325+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.052 seconds
[2025-06-19T01:54:34.703+0000] {processor.py:161} INFO - Started process (PID=54045) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:54:34.704+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:54:34.705+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:34.705+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:54:34.708+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:34.707+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:54:34.709+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:54:34.727+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.033 seconds
[2025-06-19T01:55:05.138+0000] {processor.py:161} INFO - Started process (PID=54081) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:55:05.140+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:55:05.141+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:05.140+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:55:05.144+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:05.143+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:55:05.145+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:55:05.164+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.036 seconds
[2025-06-19T01:55:35.363+0000] {processor.py:161} INFO - Started process (PID=54117) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:55:35.365+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:55:35.366+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:35.365+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:55:35.369+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:35.368+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:55:35.370+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:55:35.388+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.037 seconds
[2025-06-19T01:56:05.665+0000] {processor.py:161} INFO - Started process (PID=54153) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:56:05.668+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:56:05.671+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:05.670+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:56:05.676+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:05.674+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:56:05.677+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:56:05.698+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.043 seconds
[2025-06-19T01:56:35.941+0000] {processor.py:161} INFO - Started process (PID=54189) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:56:35.942+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:56:35.944+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:35.943+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:56:35.947+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:35.946+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:56:35.948+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:56:35.967+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.037 seconds
[2025-06-19T01:57:06.270+0000] {processor.py:161} INFO - Started process (PID=54225) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:57:06.272+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:57:06.273+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:06.273+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:57:06.276+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:06.275+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:57:06.277+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:57:06.296+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.036 seconds
[2025-06-19T01:57:36.821+0000] {processor.py:161} INFO - Started process (PID=54261) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:57:36.825+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:57:36.827+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:36.827+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:57:36.832+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:36.831+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:57:36.833+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:57:36.852+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.040 seconds
[2025-06-19T01:58:07.186+0000] {processor.py:161} INFO - Started process (PID=54297) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:58:07.188+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:58:07.189+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:07.188+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:58:07.192+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:07.191+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:58:07.193+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:58:07.213+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.035 seconds
[2025-06-19T01:58:37.531+0000] {processor.py:161} INFO - Started process (PID=54333) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:58:37.532+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:58:37.533+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:37.533+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:58:37.536+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:37.535+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:58:37.537+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:58:37.555+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.035 seconds
[2025-06-19T01:59:07.852+0000] {processor.py:161} INFO - Started process (PID=54369) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:59:07.856+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:59:07.860+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:07.859+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:59:07.864+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:07.863+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:59:07.866+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:59:07.885+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.042 seconds
[2025-06-19T01:59:38.315+0000] {processor.py:161} INFO - Started process (PID=54405) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:59:38.316+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T01:59:38.318+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:38.318+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:59:38.322+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:38.321+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T01:59:38.323+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T01:59:38.342+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.037 seconds
[2025-06-19T02:00:08.651+0000] {processor.py:161} INFO - Started process (PID=54441) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T02:00:08.652+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T02:00:08.653+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:08.652+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T02:00:08.655+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:08.655+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T02:00:08.656+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T02:00:08.670+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.026 seconds
[2025-06-19T02:00:38.906+0000] {processor.py:161} INFO - Started process (PID=54477) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T02:00:38.908+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py for tasks to queue
[2025-06-19T02:00:38.909+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:38.909+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T02:00:38.912+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:38.911+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py", line 21, in <module>
    from airflow.example_dags.plugins.workday import AfterWorkdayTimetable
ModuleNotFoundError: No module named 'airflow.example_dags.plugins.workday'
[2025-06-19T02:00:38.913+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py
[2025-06-19T02:00:38.930+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_workday_timetable.py took 0.031 seconds
