[2025-06-19T01:17:19.693+0000] {processor.py:161} INFO - Started process (PID=51405) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:17:19.695+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:17:19.696+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:19.696+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:17:19.699+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:19.698+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:17:19.700+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:17:19.714+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.029 seconds
[2025-06-19T01:17:50.155+0000] {processor.py:161} INFO - Started process (PID=51441) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:17:50.156+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:17:50.157+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:50.157+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:17:50.160+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:50.159+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:17:50.160+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:17:50.175+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.026 seconds
[2025-06-19T01:18:20.685+0000] {processor.py:161} INFO - Started process (PID=51477) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:18:20.686+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:18:20.687+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:20.687+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:18:20.690+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:20.689+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:18:20.690+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:18:20.705+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.027 seconds
[2025-06-19T01:18:51.413+0000] {processor.py:161} INFO - Started process (PID=51519) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:18:51.415+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:18:51.416+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:51.415+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:18:51.420+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:51.419+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:18:51.421+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:18:51.439+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.034 seconds
[2025-06-19T01:19:22.136+0000] {processor.py:161} INFO - Started process (PID=51555) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:19:22.137+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:19:22.138+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:22.138+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:19:22.141+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:22.140+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:19:22.142+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:19:22.159+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.031 seconds
[2025-06-19T01:19:52.571+0000] {processor.py:161} INFO - Started process (PID=51591) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:19:52.571+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:19:52.572+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:52.572+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:19:52.574+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:52.574+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:19:52.575+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:19:52.590+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.026 seconds
[2025-06-19T01:20:23.071+0000] {processor.py:161} INFO - Started process (PID=51627) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:20:23.072+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:20:23.073+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:23.073+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:20:23.076+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:23.075+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:20:23.076+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:20:23.094+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.030 seconds
[2025-06-19T01:20:53.516+0000] {processor.py:161} INFO - Started process (PID=51663) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:20:53.517+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:20:53.521+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:53.520+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:20:53.527+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:53.526+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:20:53.527+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:20:53.542+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.033 seconds
[2025-06-19T01:21:24.434+0000] {processor.py:161} INFO - Started process (PID=51699) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:21:24.435+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:21:24.437+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:24.436+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:21:24.440+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:24.439+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:21:24.440+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:21:24.457+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.032 seconds
[2025-06-19T01:21:54.873+0000] {processor.py:161} INFO - Started process (PID=51735) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:21:54.874+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:21:54.875+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:54.875+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:21:54.878+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:54.877+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:21:54.878+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:21:54.892+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.026 seconds
[2025-06-19T01:22:25.489+0000] {processor.py:161} INFO - Started process (PID=51771) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:22:25.490+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:22:25.491+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:25.491+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:22:25.493+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:25.493+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:22:25.494+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:22:25.508+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.027 seconds
[2025-06-19T01:22:56.422+0000] {processor.py:161} INFO - Started process (PID=51807) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:22:56.424+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:22:56.424+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:56.424+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:22:56.427+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:56.426+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:22:56.428+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:22:56.443+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.031 seconds
[2025-06-19T01:23:26.889+0000] {processor.py:161} INFO - Started process (PID=51843) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:23:26.890+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:23:26.891+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:26.891+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:23:26.894+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:26.893+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:23:26.895+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:23:26.909+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.027 seconds
[2025-06-19T01:23:57.561+0000] {processor.py:161} INFO - Started process (PID=51879) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:23:57.563+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:23:57.564+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:57.564+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:23:57.567+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:57.566+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:23:57.568+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:23:57.584+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.033 seconds
[2025-06-19T01:24:28.212+0000] {processor.py:161} INFO - Started process (PID=51915) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:24:28.213+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:24:28.214+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:28.214+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:24:28.217+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:28.216+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:24:28.218+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:24:28.233+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.027 seconds
[2025-06-19T01:24:58.752+0000] {processor.py:161} INFO - Started process (PID=51951) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:24:58.754+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:24:58.755+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:58.755+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:24:58.757+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:58.757+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:24:58.758+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:24:58.776+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.033 seconds
[2025-06-19T01:25:29.318+0000] {processor.py:161} INFO - Started process (PID=51987) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:25:29.319+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:25:29.320+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:29.319+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:25:29.323+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:29.322+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:25:29.323+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:25:29.341+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.030 seconds
[2025-06-19T01:25:59.961+0000] {processor.py:161} INFO - Started process (PID=52023) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:25:59.962+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:25:59.963+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:59.963+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:25:59.966+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:59.965+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:25:59.967+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:25:59.985+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.031 seconds
[2025-06-19T01:26:30.815+0000] {processor.py:161} INFO - Started process (PID=52059) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:26:30.816+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:26:30.817+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:26:30.817+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:26:30.821+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:26:30.820+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:26:30.822+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:26:30.839+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.033 seconds
[2025-06-19T01:27:01.159+0000] {processor.py:161} INFO - Started process (PID=52095) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:27:01.160+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:27:01.161+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:01.161+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:27:01.164+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:01.163+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:27:01.165+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:27:01.181+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.031 seconds
[2025-06-19T01:27:31.695+0000] {processor.py:161} INFO - Started process (PID=52131) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:27:31.696+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:27:31.697+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:31.697+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:27:31.700+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:31.699+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:27:31.701+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:27:31.716+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.029 seconds
[2025-06-19T01:28:02.424+0000] {processor.py:161} INFO - Started process (PID=52167) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:28:02.425+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:28:02.426+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:02.426+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:28:02.429+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:02.429+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:28:02.430+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:28:02.450+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.034 seconds
[2025-06-19T01:28:33.115+0000] {processor.py:161} INFO - Started process (PID=52203) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:28:33.116+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:28:33.118+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:33.117+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:28:33.121+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:33.120+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:28:33.122+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:28:33.142+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.035 seconds
[2025-06-19T01:29:04.209+0000] {processor.py:161} INFO - Started process (PID=52239) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:29:04.211+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:29:04.212+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:04.212+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:29:04.216+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:04.215+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:29:04.217+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:29:04.242+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.044 seconds
[2025-06-19T01:29:34.343+0000] {processor.py:161} INFO - Started process (PID=52275) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:29:34.344+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:29:34.346+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:34.345+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:29:34.350+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:34.349+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:29:34.351+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:29:34.373+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.041 seconds
[2025-06-19T01:30:05.281+0000] {processor.py:161} INFO - Started process (PID=52311) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:30:05.282+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:30:05.284+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:05.283+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:30:05.288+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:05.287+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:30:05.289+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:30:05.310+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.039 seconds
[2025-06-19T01:30:35.880+0000] {processor.py:161} INFO - Started process (PID=52347) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:30:35.880+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:30:35.881+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:35.881+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:30:35.884+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:35.883+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:30:35.885+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:30:35.898+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.027 seconds
[2025-06-19T01:31:06.470+0000] {processor.py:161} INFO - Started process (PID=52383) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:31:06.472+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:31:06.473+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:06.473+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:31:06.477+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:06.476+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:31:06.478+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:31:06.498+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.038 seconds
[2025-06-19T01:31:37.302+0000] {processor.py:161} INFO - Started process (PID=52419) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:31:37.303+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:31:37.304+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:37.304+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:31:37.307+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:37.307+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:31:37.308+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:31:37.330+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.037 seconds
[2025-06-19T01:32:07.849+0000] {processor.py:161} INFO - Started process (PID=52455) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:32:07.850+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:32:07.851+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:07.851+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:32:07.855+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:07.854+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:32:07.856+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:32:07.873+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.034 seconds
[2025-06-19T01:32:38.569+0000] {processor.py:161} INFO - Started process (PID=52491) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:32:38.571+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:32:38.572+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:38.572+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:32:38.576+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:38.575+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:32:38.577+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:32:38.595+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.037 seconds
[2025-06-19T01:33:09.237+0000] {processor.py:161} INFO - Started process (PID=52527) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:33:09.239+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:33:09.240+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:09.240+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:33:09.243+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:09.242+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:33:09.244+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:33:09.266+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.040 seconds
[2025-06-19T01:33:39.938+0000] {processor.py:161} INFO - Started process (PID=52563) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:33:39.939+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:33:39.940+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:39.939+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:33:39.943+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:39.942+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:33:39.944+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:33:39.965+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.038 seconds
[2025-06-19T01:34:10.768+0000] {processor.py:161} INFO - Started process (PID=52599) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:34:10.770+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:34:10.771+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:10.770+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:34:10.775+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:10.774+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:34:10.776+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:34:10.800+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.042 seconds
[2025-06-19T01:34:41.405+0000] {processor.py:161} INFO - Started process (PID=52635) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:34:41.406+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:34:41.407+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:41.407+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:34:41.411+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:41.410+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:34:41.412+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:34:41.431+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.035 seconds
[2025-06-19T01:35:12.160+0000] {processor.py:161} INFO - Started process (PID=52672) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:35:12.162+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:35:12.163+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:12.163+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:35:12.168+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:12.167+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:35:12.170+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:35:12.204+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.054 seconds
[2025-06-19T01:35:43.014+0000] {processor.py:161} INFO - Started process (PID=52708) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:35:43.016+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:35:43.017+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:43.016+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:35:43.020+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:43.019+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:35:43.021+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:35:43.051+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.046 seconds
[2025-06-19T01:36:13.830+0000] {processor.py:161} INFO - Started process (PID=52744) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:36:13.832+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:36:13.833+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:13.833+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:36:13.839+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:13.838+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:36:13.840+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:36:13.870+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.052 seconds
[2025-06-19T01:36:44.651+0000] {processor.py:161} INFO - Started process (PID=52780) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:36:44.652+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:36:44.654+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:44.654+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:36:44.658+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:44.657+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:36:44.659+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:36:44.682+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.040 seconds
[2025-06-19T01:37:15.148+0000] {processor.py:161} INFO - Started process (PID=52816) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:37:15.149+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:37:15.151+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:15.150+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:37:15.154+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:15.153+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:37:15.155+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:37:15.176+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.039 seconds
[2025-06-19T01:37:46.044+0000] {processor.py:161} INFO - Started process (PID=52852) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:37:46.045+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:37:46.046+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:46.046+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:37:46.050+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:46.049+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:37:46.053+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:37:46.076+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.042 seconds
[2025-06-19T01:38:16.649+0000] {processor.py:161} INFO - Started process (PID=52888) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:38:16.650+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:38:16.651+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:16.650+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:38:16.655+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:16.653+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:38:16.656+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:38:16.678+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.039 seconds
[2025-06-19T01:38:47.333+0000] {processor.py:161} INFO - Started process (PID=52925) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:38:47.335+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:38:47.339+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:47.338+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:38:47.347+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:47.346+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:38:47.348+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:38:47.369+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.045 seconds
[2025-06-19T01:39:18.009+0000] {processor.py:161} INFO - Started process (PID=52961) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:39:18.011+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:39:18.013+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:18.012+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:39:18.017+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:18.016+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:39:18.018+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:39:18.038+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.041 seconds
[2025-06-19T01:39:48.650+0000] {processor.py:161} INFO - Started process (PID=52997) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:39:48.652+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:39:48.653+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:48.652+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:39:48.656+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:48.655+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:39:48.657+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:39:48.677+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.036 seconds
[2025-06-19T01:40:19.293+0000] {processor.py:161} INFO - Started process (PID=53033) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:40:19.294+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:40:19.295+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:19.295+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:40:19.299+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:19.298+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:40:19.300+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:40:19.320+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.035 seconds
[2025-06-19T01:40:49.902+0000] {processor.py:161} INFO - Started process (PID=53069) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:40:49.903+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:40:49.905+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:49.904+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:40:49.909+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:49.908+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:40:49.910+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:40:49.929+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.039 seconds
[2025-06-19T01:41:20.664+0000] {processor.py:161} INFO - Started process (PID=53105) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:41:20.668+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:41:20.669+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:20.669+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:41:20.673+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:20.672+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:41:20.674+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:41:20.699+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.046 seconds
[2025-06-19T01:41:51.468+0000] {processor.py:161} INFO - Started process (PID=53141) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:41:51.471+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:41:51.473+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:51.473+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:41:51.477+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:51.476+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:41:51.478+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:41:51.500+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.043 seconds
[2025-06-19T01:42:21.699+0000] {processor.py:161} INFO - Started process (PID=53178) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:42:21.700+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:42:21.702+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:21.701+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:42:21.707+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:21.705+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:42:21.708+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:42:21.728+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.041 seconds
[2025-06-19T01:42:53.724+0000] {processor.py:161} INFO - Started process (PID=53220) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:42:53.726+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:42:53.728+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:53.727+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:42:53.733+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:53.732+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:42:53.734+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:42:53.760+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.051 seconds
[2025-06-19T01:43:24.395+0000] {processor.py:161} INFO - Started process (PID=53256) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:43:24.396+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:43:24.397+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:24.397+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:43:24.402+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:24.401+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:43:24.404+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:43:24.434+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.050 seconds
[2025-06-19T01:43:54.630+0000] {processor.py:161} INFO - Started process (PID=53292) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:43:54.632+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:43:54.635+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:54.634+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:43:54.640+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:54.638+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:43:54.641+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:43:54.673+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.054 seconds
[2025-06-19T01:44:24.882+0000] {processor.py:161} INFO - Started process (PID=53328) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:44:24.884+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:44:24.886+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:24.885+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:44:24.890+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:24.889+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:44:24.892+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:44:24.917+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.046 seconds
[2025-06-19T01:44:55.336+0000] {processor.py:161} INFO - Started process (PID=53365) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:44:55.338+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:44:55.339+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:55.339+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:44:55.345+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:55.343+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:44:55.347+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:44:55.378+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.057 seconds
[2025-06-19T01:45:25.650+0000] {processor.py:161} INFO - Started process (PID=53401) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:45:25.652+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:45:25.654+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:25.653+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:45:25.659+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:25.657+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:45:25.660+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:45:25.688+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.053 seconds
[2025-06-19T01:45:56.544+0000] {processor.py:161} INFO - Started process (PID=53437) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:45:56.546+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:45:56.549+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:56.548+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:45:56.554+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:56.553+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:45:56.556+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:45:56.588+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.060 seconds
[2025-06-19T01:46:29.066+0000] {processor.py:161} INFO - Started process (PID=53473) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:46:29.080+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:46:29.090+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:29.090+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:46:29.113+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:29.111+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:46:29.134+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:46:29.181+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.136 seconds
[2025-06-19T01:46:59.665+0000] {processor.py:161} INFO - Started process (PID=53509) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:46:59.666+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:46:59.667+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:59.667+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:46:59.672+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:59.671+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:46:59.673+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:46:59.700+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.048 seconds
[2025-06-19T01:47:29.849+0000] {processor.py:161} INFO - Started process (PID=53545) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:47:29.851+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:47:29.852+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:29.851+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:47:29.856+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:29.855+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:47:29.858+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:47:29.896+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.060 seconds
[2025-06-19T01:48:00.109+0000] {processor.py:161} INFO - Started process (PID=53581) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:48:00.111+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:48:00.112+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:00.112+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:48:00.118+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:00.117+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:48:00.120+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:48:00.149+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.053 seconds
[2025-06-19T01:48:30.533+0000] {processor.py:161} INFO - Started process (PID=53617) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:48:30.535+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:48:30.537+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:30.536+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:48:30.543+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:30.540+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:48:30.545+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:48:30.573+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.054 seconds
[2025-06-19T01:49:00.646+0000] {processor.py:161} INFO - Started process (PID=53653) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:49:00.648+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:49:00.649+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:00.649+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:49:00.654+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:00.653+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:49:00.655+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:49:00.686+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.054 seconds
[2025-06-19T01:49:31.311+0000] {processor.py:161} INFO - Started process (PID=53689) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:49:31.313+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:49:31.315+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:31.314+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:49:31.321+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:31.320+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:49:31.322+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:49:31.351+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.055 seconds
[2025-06-19T01:50:01.470+0000] {processor.py:161} INFO - Started process (PID=53725) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:50:01.471+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:50:01.473+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:01.473+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:50:01.479+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:01.477+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:50:01.481+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:50:01.506+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.047 seconds
[2025-06-19T01:50:32.648+0000] {processor.py:161} INFO - Started process (PID=53761) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:50:32.650+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:50:32.651+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:32.651+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:50:32.655+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:32.654+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:50:32.657+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:50:32.682+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.045 seconds
[2025-06-19T01:51:02.741+0000] {processor.py:161} INFO - Started process (PID=53797) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:51:02.742+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:51:02.743+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:02.743+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:51:02.748+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:02.747+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:51:02.749+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:51:02.772+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.043 seconds
[2025-06-19T01:51:33.410+0000] {processor.py:161} INFO - Started process (PID=53834) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:51:33.411+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:51:33.412+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:33.412+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:51:33.417+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:33.415+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:51:33.418+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:51:33.443+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.046 seconds
[2025-06-19T01:52:04.167+0000] {processor.py:161} INFO - Started process (PID=53870) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:52:04.168+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:52:04.170+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:04.169+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:52:04.175+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:04.173+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:52:04.177+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:52:04.203+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.049 seconds
[2025-06-19T01:52:34.663+0000] {processor.py:161} INFO - Started process (PID=53906) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:52:34.664+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:52:34.665+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:34.665+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:52:34.670+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:34.669+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:52:34.672+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:52:34.692+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.041 seconds
[2025-06-19T01:53:04.964+0000] {processor.py:161} INFO - Started process (PID=53942) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:53:04.965+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:53:04.966+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:04.966+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:53:04.970+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:04.969+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:53:04.972+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:53:04.991+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.037 seconds
[2025-06-19T01:53:35.262+0000] {processor.py:161} INFO - Started process (PID=53978) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:53:35.264+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:53:35.265+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:35.264+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:53:35.269+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:35.268+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:53:35.270+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:53:35.289+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.035 seconds
[2025-06-19T01:54:05.618+0000] {processor.py:161} INFO - Started process (PID=54015) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:54:05.620+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:54:05.621+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:05.621+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:54:05.626+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:05.625+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:54:05.627+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:54:05.648+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.041 seconds
[2025-06-19T01:54:36.006+0000] {processor.py:161} INFO - Started process (PID=54051) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:54:36.007+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:54:36.008+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:36.008+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:54:36.012+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:36.011+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:54:36.013+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:54:36.036+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.040 seconds
[2025-06-19T01:55:06.394+0000] {processor.py:161} INFO - Started process (PID=54087) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:55:06.395+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:55:06.397+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:06.396+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:55:06.400+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:06.399+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:55:06.401+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:55:06.421+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.036 seconds
[2025-06-19T01:55:36.604+0000] {processor.py:161} INFO - Started process (PID=54123) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:55:36.605+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:55:36.606+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:36.606+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:55:36.610+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:36.609+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:55:36.611+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:55:36.633+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.039 seconds
[2025-06-19T01:56:07.027+0000] {processor.py:161} INFO - Started process (PID=54159) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:56:07.029+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:56:07.030+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:07.030+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:56:07.034+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:07.033+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:56:07.036+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:56:07.058+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.041 seconds
[2025-06-19T01:56:37.232+0000] {processor.py:161} INFO - Started process (PID=54195) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:56:37.233+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:56:37.235+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:37.234+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:56:37.238+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:37.237+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:56:37.239+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:56:37.257+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.034 seconds
[2025-06-19T01:57:07.509+0000] {processor.py:161} INFO - Started process (PID=54231) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:57:07.511+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:57:07.512+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:07.512+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:57:07.516+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:07.515+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:57:07.517+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:57:07.536+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.037 seconds
[2025-06-19T01:57:38.107+0000] {processor.py:161} INFO - Started process (PID=54267) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:57:38.108+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:57:38.110+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:38.109+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:57:38.114+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:38.113+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:57:38.115+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:57:38.136+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.041 seconds
[2025-06-19T01:58:08.436+0000] {processor.py:161} INFO - Started process (PID=54303) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:58:08.437+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:58:08.439+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:08.438+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:58:08.443+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:08.442+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:58:08.444+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:58:08.466+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.041 seconds
[2025-06-19T01:58:38.779+0000] {processor.py:161} INFO - Started process (PID=54339) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:58:38.780+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:58:38.782+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:38.781+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:58:38.785+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:38.784+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:58:38.786+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:58:38.804+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.035 seconds
[2025-06-19T01:59:09.162+0000] {processor.py:161} INFO - Started process (PID=54375) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:59:09.163+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:59:09.164+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:09.164+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:59:09.168+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:09.167+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:59:09.169+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:59:09.188+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.036 seconds
[2025-06-19T01:59:39.590+0000] {processor.py:161} INFO - Started process (PID=54411) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:59:39.591+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T01:59:39.592+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:39.592+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:59:39.596+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:39.595+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:59:39.597+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T01:59:39.615+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.035 seconds
[2025-06-19T02:00:09.908+0000] {processor.py:161} INFO - Started process (PID=54447) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T02:00:09.909+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T02:00:09.910+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:09.910+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T02:00:09.913+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:09.912+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T02:00:09.914+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T02:00:09.930+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.030 seconds
[2025-06-19T02:00:40.238+0000] {processor.py:161} INFO - Started process (PID=54483) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T02:00:40.239+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py for tasks to queue
[2025-06-19T02:00:40.240+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:40.240+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T02:00:40.243+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:40.242+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py", line 57, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T02:00:40.244+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py
[2025-06-19T02:00:40.260+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_assets.py took 0.031 seconds
